function vecq = gotler(~,q,baseT,baseTdash,baseU,kappa,beta,khat,...
    intbaseT)
    vecq(1) = q(2);
    vecq(2) = 2*q(2)*baseTdash./baseT ...
        + baseT^2*(khat^2)*q(1) ...
        + (0.5*kappa*(baseU^2)-intbaseT)*(baseTdash*(khat^2)*q(1)/(beta^2));
    
    